### ISSUE TITLE
Question about virtualDisk : Since & Until 

### ISSUE THREAD

**Issue by AntoineThebaud** [Tintri/tintri-rest-api#11]
Hello,

I'm currently struggling with the API.
I'm trying to retrieve the virtualDisk stats for the last minute, thus I tried to override the default time range (past 7 days) by using `since` & `until` parameters.

But when using them in the request, either it's having no effect or I'm getting nothing (`items` is empty).

This is how I call the API
`/api/v310/virtualDisk?since=2019-10-28T12:00:00.000&until=2019-10-29T12:00:00.000`

What am I doing wrong here ?

Thanks in advance for your help.

**Comment by rehrhart** [comment]
Hi Antoine,

The API should be called like this: 
`GET /v310/virtualDisk/{vmId}/{vdiskId}/statsHistoric`  Go [here](https://tintri.github.io/tintri-rest-api/client/http/docs/gen_api_doc/jaxrs/v310/v310/virtualDisk/%7BvmId%7D/%7BvdiskId%7D/statsHistoric/index.html) for more details.  As you can see, you will need the VM ID and the virtual disk ID.
Reviewing the APIs, I think this will be a 2 step process:
 * Get the VM ID or UUID from GET vm API
 * Get the virtual disks and search the list for the VM ID.

I would also look the [get VM stat example](https://github.com/Tintri/tintri-api-examples/blob/master/get_vm_stats.py) for some context.  Even though you are attempting to get virtual disk statistics instead of VM statistics the design will be similar.

Regards,
   Rick

**Comment by AntoineThebaud** [comment]
Hello Rick,

Actually I was looking for an API call to get the most recent stat for all virtual disks at once (like /statsRealtime but for every objects). Seems it's not possible so yes, I will need as you described to go through a 2 step process.

Thanks a lot for your help.

R,
Antoine
